require(httr)
require(tidyverse)
require(data.table)
require(glue)
require(here)
require(janitor)
require(curl)
require(jsonlite)
require(furrr)
require(stringi)
require(reclin)
require(fst)
require(lubridate)
require(tictoc)
require(ggplot2)
require(svglite)
require(maps)
require(cowplot)
require(mapproj)
require(gganimate)
require(scales)

here <- here()
`%notin%` <- Negate(`%in%`)
`%notlike%` <- Negate(`%like%`)

dl_dir <- glue("{here}/data/school_websites")
json_dir <- glue("{here}/data/school_websites/json")
